### ISSUE TITLE
MacOS: Search path for SoundFont

### ISSUE THREAD

**Issue by blurbler27** [lenmus/lenmus#117]
In the MacOS build, the default search path for the soundfont (FluidR3_GM.sf2) is in the build directory, _not_ in the app bundle. This could be a problem if it is desired to create an app bundle for distribution. 
![Configuration_options](https://user-images.githubusercontent.com/32274358/85240100-83a54b80-b3fc-11ea-93a1-d7b221b66f13.png)

**Comment by cecilios** [comment]
The default path is provided by Paths object:
https://github.com/lenmus/lenmus/blob/c063f41986c4dee7d55c8498c5c5628770575505/src/sound/lenmus_midi_server.cpp#L227-L235

An, in the Path object, according to these lines:

https://github.com/lenmus/lenmus/blob/c063f41986c4dee7d55c8498c5c5628770575505/src/globals/lenmus_paths.cpp#L207-L221

https://github.com/lenmus/lenmus/blob/c063f41986c4dee7d55c8498c5c5628770575505/src/globals/lenmus_paths.cpp#L296-L306

it should be pointing either to `LENMUS_SOUNDFONT_PATH` if not empty or to `Resources/res/sounds`.

The value for `LENMUS_SOUNDFONT_PATH` is in lenmus_config.h file and is provided by CMakeLists.txt. When running cmake it displays some log lines. Look at this log to see if we can get more information. By the way, could you send me also the log? Thank you.

Another issue, I've observed that you have included in the code lines such as `#if __APPLE__`. It is better not to depend on specific macros, e.g. `__APPLE__`, defined by each compiler as these macros could not exist when using another compiler in another platform. So, please, use instead `#if (LENMUS_PLATFORM_MAC == 1)`. Thank you.

**Comment by blurbler27** [comment]
Yes, I noticed that LENMUS_SOUNDFONT_PATH was set in lenmus_config.h.  On one earlier trial I tried changing this to define it as "", and then it picked up the version in Resources/res/sounds correctly.  I'm attaching lenmus_config.h.
[lenmus_config.h.txt](https://github.com/lenmus/lenmus/files/4815062/lenmus_config.h.txt)
Does cmake keep log files somewhere?  While cmake was running, I saw the lines 
```
-- LENMUS_SOUNDFONT_PATH=/Users/rbyerly/devel/xcodev/lenmus-3/lenmus/res/sounds
lenmus_config.h configuration:
-- LENMUS_INSTALL_ROOT=/usr/local/
-- LENMUS_TEST_SCORES_PATH="/Users/rbyerly/devel/xcodev/lenmus-3/lenmus/scores/samples/test_set/"
-- LENMUS_SOUNDFONT_PATH=/Users/rbyerly/devel/xcodev/lenmus-3/lenmus/res/sounds
Lomse configuration
```
which refers to files in the build directory.

I was a little worried about the consequences of editing CMakeLists.txt to set
```
elseif(APPLE)
    set( LENMUS_PLATFORM_WIN32 "0")
    set( LENMUS_PLATFORM_UNIX "0") 
    set( LENMUS_PLATFORM_MAC "1")
endif()
```
because I wasn't sure what unintended consequences there would be of setting LENMUS_PLATFORM_UNIX to 0.  In most respects, Apple and Linux are the same.  They diverge in only a few places.  That was why I used the __APPLE__ variable, but I understand why that could be a problem.

**Comment by cecilios** [comment]
> Does cmake keep log files somewhere? While cmake was running, I saw the lines

No to my knowledge. So just copy from screen or do  `cmake .... > log.txt`

> On one earlier trial I tried changing this to define it as "", and then it picked up the version in Resources/res/sounds correctly.

Perhaps that's the best and simplest solution for macOS package and is perfectly valid. So change CMakeList.txt for defining it empty for APPLE.

> I was a little worried about the consequences of editing CMakeLists.txt to set 
>
> elseif(APPLE)
>     set( LENMUS_PLATFORM_WIN32 "0")
>     set( LENMUS_PLATFORM_UNIX "0") 
>     set( LENMUS_PLATFORM_MAC "1")
> endif()

When I did changes in CMakeLists.txt and added the `LENMUS_PLATFORM_MAC` macro, I reviewed lenmus source code and tried to add this macro at relevant places so that I do not expect any problem. But, in any case, we have to try and to fix any possible issues. For lenmus, the meaning of these macros is:

- `LENMUS_PLATFORM_WIN32==1` : the program is being compiled for Windows.
- `LENMUS_PLATFORM_MAC==1` : the program is being compiled for Apple
- `LENMUS_PLATFORM_UNIX==1` : the program is being compiled for other Unix systems.
 
These macros are exclusive, so only one of them must be 1.

**Comment by blurbler27** [comment]
1.  I've gone through the source code and gotten rid (mostly) of the __APPLE__ macros, replacing them with the LENMUS_PLATFORM_* macros.  I used something like (LENMUS_PLATFORM_UNIX==1 || LENMUS_PLATFORM_MAC==1) for sections where both apply.

**Comment by blurbler27** [comment]
1.  I've gone through the source code replacing (mostly) the ``__APPLE__`` macros and using ``LENMUS_PLATFORM_*`` macros as appropriate.  I used ``LENMUS_PLATFORM_UNIX==1 || LENMUS_PLATFORM_MAC == 1`` for sections where both applied.  Tests indicate this is working.

2. There were a few occurrences of the ``__APPLE__`` macro that looked like code borrowed from someone else, or code used by cmake in determining the platform type (namely in ``wxsqlite3.cpp`` and ``ioapi.c``).  These I left alone.

3. I explicitly set ``LENMUS_SOUNDFONT_PATH`` to ``""`` in CMakeLists.txt for the Mac platform.  This works.

So maybe this issue can be closed for now.  In the long run, for a less confusing installation, maybe this can be handled in a way similar to the way the Bravura font is currently being handled.

**Comment by cecilios** [comment]
Thank you!

> ... namely in wxsqlite3.cpp and ioapi.c ...

Good! Never touch third party code!

Could you please do a Pull Request with these changes to close this issue? Thank you.
