### ISSUE TITLE
MacOS: latest version -- issue opening books in various languages

### ISSUE THREAD

**Issue by blurbler27** [lenmus/lenmus#121]
I today just downloaded the latest version from github.  The first issue is that when language is set to English and I select the "Available books" link, I get this:
![Issue1](https://user-images.githubusercontent.com/32274358/85923504-186ed580-b851-11ea-9108-c305089398c8.png)
and the book opens in Spanish.

When I change the default language to Spanish, I get a normal appearing book menu, but when I try to open a book, I get the "Invalid Real Number" window again:
![Issue3](https://user-images.githubusercontent.com/32274358/85923558-a6e35700-b851-11ea-98c3-a3d8ca9d6854.png)
although the book will open correctly when I click "Aceptar".

I got similar behavior when I tried the other languages.  (Incidentally, when I set the language to Deutsch -- German, the books open in English.)

On the previous version (from last week), the "Available Books" menu is correct in the English version, but I'm still getting the "Invalid Real Number" window.

**Comment by cecilios** [comment]
Oh! My fault. I've started with a new book and for testing it I replaced book L1_MusicReading. And in latest PR I inadvertently, uploaded this change. I will fix immediately. Thank you!

**Comment by cecilios** [comment]
OK. Now it is fixed. This new book is just a draft, in Spanish. No translations yet. For the other eBooks, some are not translated. For instance, in German translation I think that only the GUI and the General Exercises book are translated. It was the minimum I required from translators to include a new translation and, sometimes, they abandon after this initial step.

**Comment by cecilios** [comment]
The 'invalid real number' error is because I fixed the program that generates the ebooks but only regenerated the English ones. So, in all other languages you will get that error

**Comment by cecilios** [comment]
I've decided to close this issue since it is an old one and it should be resolved with last release. Nevertheless, more testing is needed and I can reopen it if needed.
