### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [lenmus/lenmus#125]
Thank you very much for the program released under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D1%81%D0%B8%D0%BD%D1%82%D0%B5%D0%B7/lenmus-phonascus.html).

Please do not abandon the project, this is a very interesting program!

Will the releases be published here?

**Comment by cecilios** [comment]
Thank you for your words.

New releases are always published here and the website download page is updated. As to the future of the project ... the code is complex and there are no developers collaborating, so it is technically death.
