### ISSUE TITLE
Contributing to documentation

### ISSUE THREAD

**Issue by bkmgit** [lenmus/lenmus#128]
Would be helpful if information on how one can contribute to the documentation on GitHub could be provided. As an example the page [Building on Linux](http://www.lenmus.org/en/phonascus/building-linux) is targeted towards Debian/Ubuntu. It would be nice to have the following for RPM based distributions (Tested on Fedora Linux):

```sh
dnf -y groupinstall "Development Tools"
dnf -y install cmake
dnf -y install portmidi-devel sqlite-devel
dnf -y install freetype-devel libpng-devel zlib-devel wxGTK3-devel
dnf -y install fluidsynth-devel unittest-cpp-devel
dnf -y install fontconfig-devel
```

If Png++ is not available for your distribution, download and install it from [here](http://download.savannah.nongnu.org/releases/pngpp/)

**Comment by cecilios** [comment]
Thank you very much for your feedback and the instructions for RPM based distros. I totally agree with you on the need to have build instructions in this repo. I will fix this ASAP.

Current public documentation is in two places:
- this repo, folder /docs
- the website.

Unfortunately build instructions are not in the repo but in the website. I will move them here and point the site to here.

**Comment by cecilios** [comment]
Documentation added to GitHub and updated. And website also updated.
Closing.
