### ISSUE TITLE
Potential typo in Theory and Harmony study book

### ISSUE THREAD

**Issue by AObuchow** [lenmus/lenmus#137]
I was reading `3.3 Tones. Major Scales` from the Theory and Harmony study book and think there might be a typo in the sentence below:
![image](https://user-images.githubusercontent.com/10300119/122704162-1dc2ee00-d221-11eb-8c08-afc0fc4290a9.png)

Is it supposed to instead read "reminds you of" instead of "remains you"?

If so, I'd be glad to try and submit a small PR to correct this, if desired :)

Side note: I'm really loving lenmus so far! It seems to be exactly what I was looking for in terms of music learning software :)

**Comment by cecilios** [comment]
Thanks for reporting. I'm not native English speaker and so the English texts are probably full of typos. Please, feel free to report what you find. I'll be glad to correct the texts!

I prefer that you just report the changes: e.g. typo in book X, theme Y: change "this text" to "this other text". It is much simpler for you as making a PR takes more time and, in any case, I also have to change the fixed text in the PO file, for not invalidating the translations.

Thanks again for reporting
