### ISSUE TITLE
Website spelling error on home page

### ISSUE THREAD

**Issue by morrismichaelc** [lenmus/lenmus#140]
I've just begun looking at music software; I have not tried yours yet, but I deeply appreciate the open source community and thought maybe I could contribute one small bit of assistance: On your website, there is  a misspelling of "students" on the homepage, top right corner by the download button. The last "t" is omitted, leaving "studens". Not a big deal, but doesn't fit with the otherwise very professional looking site.

Thanks for sharing your work!

![image](https://user-images.githubusercontent.com/47469340/123856679-3a70bd00-d8d6-11eb-9ba6-65354596a116.png)

**Comment by cecilios** [comment]
Thanks for reporting! An stupid typo indeed! I will try to fix it today. Thank you.

**Comment by cecilios** [comment]
Fixed!
