### ISSUE TITLE
Typo in Music Reading 6.

### ISSUE THREAD

**Issue by Meowpolice** [lenmus/lenmus#33]
Near the botton of 6. Time signatures it says "But remember that rhythm is something natural that exists by **itsel** in the music."

**Comment by Meowpolice** [comment]
Also in 12. The eighth note it says "are shown in the **followig** score"

**Comment by cecilios** [comment]
@Meowpolice, Thanks for reporting these typos. Probably you will find more. I think the best approach would be to prepare an script for running a checkspeller  on all translatable texts, so to ensure that English spelling is correct. This will not ensure correct syntax but will improve quality and set up more quality assurance procedures.

**Comment by cecilios** [comment]
After some tests to create an script using 'aspell' check speller, I thing it is more practical for now to check files by hand than to prepare an script. 

I have created issue #xx to create in future this quality assurance script. For now I will check, by hand, all the files for the lessons.

Files to check:

- [x] L1_MusicReading
- [ ] L2_MusicReading
- [ ] TheoryHarmony
- [ ] GeneralExercises
