### ISSUE TITLE
Integrate in Debian

### ISSUE THREAD

**Issue by cecilios** [lenmus/lenmus#4]
It would be nice to get LenMus to be an standard package in Debian.

**Comment by pandamasta** [comment]
Hi Cecilios,

I have updated the bug report to "Intent to Package"
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=480510 

I'll review the package at least for the next weak, send to mentor, and find a sponsor.

I let you know
Cheers,Aurelien

**Comment by cecilios** [comment]
Great! Thank you very much.

**Comment by cecilios** [comment]
I suspect that creating the debian package is going to require a lot of effort, so lets go step by step.

Some lintian issues look like something easy to solve. You could work on them as we clarify the others.

Others will require more work:

- Issue #42 (Lintian issue: arch-dep-package-has-big-usr-share) will require to split the package into several packages. This will affect to all the work to do, so this must be one of the first issues to analyse and to agree on the solution.

- Issues #48 and #49 are difficult to solve. Also need to agree on the solution before doing anything.

- Issue #47: my opinion is that this is not an issue and we should do nothing. Is it possible for debian mentors to accept the package with this lintian issue raised?

- All others looks easy to solve, although some would require some work. In particular issue #41 will create a new dependency on Java packages.


Therefore, my proposal is to start by document all the issues and doing some research about how to solve them. Most of the lintian issues are already documented in the lenmus issues tracker and I have added my preliminary analysis of what to do. Let's discuss on each issue, get clearer ideas and agree on the solution for each issue. While doing this, we can work on solving issues that are clear and on preparation of coming work.

In any case all this effort and the changes we have to do must be compatible with building for other platforms. For instance, if for solving issue #41 we create a dependency on java packages, either:
- ensure that the solution is platform independent, or
- ensure that the solution can be also valid for other platforms with appropriate changes in makefiles.

Finally, all this effort must not prevent that we can continue developing lenmus and providing packages as we do now. In particular two issues came to my mind in this moment:

1. You say that _"it's seems not good to carry debian/ in the main branch, it's better to maintain it in a separate branch"_. Probably yes but the problem we have is that folder /debian is a requirement from Launchpad for creating the packages for Lenmus PPA. Can not be removed until either lenmus is available as a package in Debian distros or we can find a way to automatically create the packages for the different ubuntu versions, so that we can upload the packages to PPA. Probably another folder is needed for building for debian but for now will have to have a different name!

2. If we split lenmus package into several packages, CMakeLists.txt file should have always the option of building everything in a single package (as it is done now). This is now required for Travis and for Launchpad builds for PPA.

Instead of continue by private email I would suggest add comments on each issue. In this way we will avoid having to look through several mails to find the discussions about a particular issue. For general comments about building the package we could comment this issue. Nevertheless feel free to send me private emails when you like.
 
Regards,
Cecilio

**Comment by cecilios** [comment]
I will not do this myself so it is useless to have this issue open as I cannot do it.
