### ISSUE TITLE
man page should be written

### ISSUE THREAD

**Issue by pandamasta** [lenmus/lenmus#40]
It could be interesting to have a man page for lenmus

Lintian give a warning for this:
W: lenmus: binary-without-manpage usr/bin/lenmus

**Comment by cecilios** [comment]
I can write a man page but .. it is a GUI application! I'm not sure what to write. What it is expected to contain? 
I will try to look the man page for other applications, for inspiration. Anyway if you can suggest examples of a man pages for application not accepting parameters, it will be of help. 
Thank you.

**Comment by cecilios** [comment]
Solving this is just modifying CMakeLists.txt. See:
http://stackoverflow.com/questions/3375341/man-page-generation-packaging-installation-with-cmake

**Comment by gouchi** [comment]
For example [tagainijisho](https://packages.debian.org/jessie/tagainijisho).

**Comment by cecilios** [comment]
Man page is already writen. Uploading it is pending for deciding the best folder for placing it: root floder? docs? debian? other?
I postponed this decision in case that for creating the Debain package there were a preferred location. But as the way for adding it to package is decided in CMakeLists.txt (see my previous comment) I think that any location is ok. In any case, this task is managed by panadamasta, so I'm waiting suggestions/feedback.
