### ISSUE TITLE
Packages and installers

### ISSUE THREAD

**Issue by cecilios** [lenmus/lenmus#5]
We must improve and maintain the packages generation and to develop a Windows installer.

It is necessary to promote LenMus in Debian, so that LenMus become a standard package in Debian. This would open the door for standard inclusion in other distros. And this could also generate interest to attract more developers. See #4.

Basically we have to work on Debian (.deb) and Red Hat (.rpm) packages. And automate the process of generating these packages to systematically generate them when LenMus repositories are updated. It would be nice if someone with good knowledge in making Linux packages for the most common distributions could join the project.

When a version for Apple is ready, it will be necessary to prepare also an installer for that platform.

And we must maintain the Windows version and enhance the installer.

**Comment by kolewu** [comment]
I maintain a version for Archlinux: https://aur.archlinux.org/packages/lenmus/

**Comment by cecilios** [comment]
Oh! Yes! I now remember you! We had a conversation last summer because there were a problem to install  LenMus.  When you post the first comment about the lomse version issue I had the feeling that your name was familiar to me, but I was not able to remember.

In fact I added your package to this page: http://www.lenmus.org/en/phonascus/download-linux

 Sorry! I'm becoming very forgetful with the age. And thanks very much for your help!

**Comment by kolewu** [comment]
Oh yes, I do know this little problems ;-)

**Comment by cecilios** [comment]
Tis issue has nothing doable.
I opened this issue time ago, but I'm not a package maintainer for any distro and I will not work on issues related to specific details of each Linux distro unless the issue is open by a real package maintainer.
