### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by baimafeima** [lenmus/lenmus#62]
Hello, first of all thank you for taking the time to develop LenMus in your free time. Some time ago I have requested LenMus Phonascus to be added to the repositories of my main operating system, Solus: https://dev.solus-project.com/T1074
Currently, the issue is on hold due to technical issues in getting it to build. Do you already know when you will be able to release the next version?

**Comment by cecilios** [comment]
I apologize for the delay. I do not have plans for a release soon but
LenMus is stable and should build without problems. Please, send me
information about the build issues you have found. I'm on vacation and I
can't look at any issues at this moment. But in September I could help with
any issue.

**Comment by donpdonp** [comment]
an updated build for ubuntu 18.04 would be appreciated. this is the error when installing the last lenmus release on 18.04

```
lenmus is already the newest version (5.4.1-0~727~ubuntu16.04.1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 lenmus : Depends: libboost-date-time1.58.0 but it is not installable
          Depends: libboost-system1.58.0 but it is not installable
          Depends: libboost-thread1.58.0 but it is not installable
          Depends: libpng12-0 (>= 1.2.13-4) but it is not installable
          Depends: libportmidi0 but it is not going to be installed
          Depends: libwxbase3.0-0v5 (>= 3.0.2+dfsg) but it is not going to be installed
          Depends: libwxgtk3.0-0v5 (>= 3.0.2+dfsg) but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by cecilios** [comment]
While investigating LenMus status at launchpad, I've discovered that someone did the work of importing LenMus project and building packages for Ubuntu 18. This is the PPA:

https://code.launchpad.net/~drisena/+archive/ubuntu/ppa/+packages

I have not tested them but if you are in a hurry you could try them, as updating the project and preparing packages for latest Ubuntu versions will take me a few days.

**Comment by donpdonp** [comment]
I tried that PPA and it appears to work fine. thanks!!

**Comment by cecilios** [comment]
PPA now updated with packages for the different Ubuntu versions
