### ISSUE TITLE
Path duplication on install

### ISSUE THREAD

**Issue by lgbaldoni** [lenmus/lenmus#73]
When running `DESTDIR=/home/user/foo make install`, samples are installed into /home/user/foo/home/user/lenmus/samples.
It appears to be originating from https://github.com/lenmus/lenmus/blob/master/CMakeLists.txt#L838: is this the desired behaviour?

**Comment by cecilios** [comment]
At install time some sample scores are placed in ~/lenmus/samples. But they are not used by the program and are not needed. The purpose of line https://github.com/lenmus/lenmus/blob/master/CMakeLists.txt#L838 : 

    set(SAMPLES_DIR $ENV{HOME}/${CMAKE_PROJECT_NAME} )

Is to point to ~/lenmus folder when installing these samples in the final user machine.

If you would like to install to a temporary directory for testing or packaging, the samples could be placed anywere as **they are not used**. But if you run the program it will access the user home directory, create some folders and place some data there, in particular:

- User depedent configuration files:	~/.config/lenmus/x.x.x
- Logs & temporal files, per user: ~/lenmus/temp

The path you are getting by running `make DESTDIR=/home/user/foo install` should be `/home/user/foo/home/user/<your-user>/lenmus/samples` and not `/home/user/foo/home/user/lenmus/samples` as you report. But in any case I think it is irrelevant. Does this causes any problem? Can you elaborate more on the problem or suggest some fix?

I am probably missing some context here as I do not have experience in preparing installation packages.

**Comment by cecilios** [comment]
Fixed in PR #76
