### ISSUE TITLE
external midi test works, no sound in books

### ISSUE THREAD

**Issue by jasonwheritage** [lenmus/lenmus#94]
I have just installed: lenmus-all version 5.6.1 
As far as I can tell, I have no internal synth installed, however i should be able to use my keyboard.
I connected my keyboard through USB, lenmus recognises the external synth of my keyboard, and I can cycle through some of the acoustic piano sounds, they test ok. 
When I go to the General Exercises book and try an aural lesson, the sound does not play. I check again that I have the external synth selected, which it is, still no luck.

**Comment by cecilios** [comment]
Thanks for reporting.
I've checked and I can confirm the bug.
I'm going to try to fix it today and prepare new Ubuntu packages.

**Comment by cecilios** [comment]
Sorry! I checked this too quickly! I think that the program works ok. When you closes the Sound Options window, after configuring the external synthesizer, do you click on the 'Accept' button?

**Comment by cecilios** [comment]
Also take into account that when you stop running LenMus and remove the midi keyboard, the next time you run LenMus the midi keyboard must have been previously connected. Otherwise, when LenMus starts, will not detect previuosly selected external synth and will change the settings.

**Comment by cecilios** [comment]
Any feedback on this? I would like to confirm if there is a bug to solve this as soon as posible. I've not been able to reproduce this.

By the way, you don't need an external synthesizer. The internal synthesizer refers to the one in the LenMus program not to one in your machine. LenMus now includes an internal synthesizer that should always work with the default configuration.

**Comment by jasonwheritage** [comment]
Thanks for the reply, I now have it working. Unfortunately I did not have the "canberra-gtk-module" installed. I ran:
`sudo apt-get install libcanberra-gtk-module`
and it now works. Sorry for the trouble.
