### ISSUE TITLE
lenmus 5.6.1 build fails

### ISSUE THREAD

**Issue by lgbaldoni** [lenmus/lenmus#97]
On openSUSE Tumbleweed wiht wxWidgets 3.0.4.
See [log](https://github.com/lenmus/lenmus/files/4370835/lenmus561_wxString.txt).

**Comment by cecilios** [comment]
PR #99 should fix this.
 In my machine (Mint 19) using wxWidgest 3.0.4, the code with this fix and withou it, compiles ok. Also in Travis, in Ubuntu PPA (wxWidgets 3.0.5) and in Fedora 31.

I have not tested the fix in OpenSUSE and I don't know why it failed in OpenSUSE, probably wxWidgets is build with differentet options for wxString but, in any case, this PR should fix it.

**Comment by lgbaldoni** [comment]
I can confirm it builds now.
